((emacs-lisp-mode . ((fill-column . 80)
                     (indent-tabs-mode . nil)
                     (sentence-end-double-space . t)
                     (elisp-lint-indent-specs
                      . ((org-autotask-with-org-node-with-url . 1)
                         (org-autotask--test-fixture . 1)
                         (org-autotask--buffer-test . 1)
                         (org-autotask--clock-in-action-test . 2)
                         (org-autotask--with-replaced-action-fn . 3)
                         (org-autotask--with-temp-org-agenda-files . defun)
                         (org-autotask-test--with-temp-archive . defun))))))
