#+TITLE: org-autotask: building agendas and Org automation

* Introduction

This is a set of building blocks for a task management implementation in Org
following GTD (Getting Things Done), with focus on agenda views for contexts and
automation, for clocking and writing own ones in Elisp. Assumes familiarity with Org.

* Example

TODO

* Concepts

- A /list/ is a collection of items, task or otherwise, as in GTD. A list
  has an Org tag for its items, a quick selection character, and a description.
- A /context/ is a place where some TODO items, but not others, can be done. An item
  can belong to only one context. Items are assigned to contexts with Org tags. One
  special context is "waiting-for" for tasks that somebody else have to complete.
- A /project/ contains items (subprojects or TODO items) in its subtree. It is tagged
  with the configurable project list-specific tag and also has a TODO entry keyword.
- /Someday-maybe/ items are tagged with their category tag, which is configured to be
  inheritable in Org, thus either the items themselves or one of the outline
  ancestors have to be tagged with it. Items can be moved from and to this state by
  refiling.

* Configuration

Since this package expects certain Org configuration, some variables should be left
untouched, or they will be overwritten:
- ~org-todo-repeat-to-state~
- ~org-enforce-todo-dependencies~
- ~org-stuck-projects~

Some other variables have to be set by user and then will be checked/modified during
setup:
- ~org-todo-keywords~ must contain all of the ~org-autotask~-configured keywords.
- ~org-use-tag-inheritance~ must either be ~t~, a string that matches the
  someday/maybe tag, or be a list. If it's a list, the tag for someday/maybe will be
  added there.
- ~org-tag-alist~ must not have anything related to contexts, projects, and
  someday/maybe, and they will be added to it.

Tasks (and some other items such projects) are grouped into lists, as in GTD. The
list-related customization is:
- ~org-autotask-contexts~: An (elisp) list of GTD contexts, except for the waiting-for
  one. They, together with the waiting-for context, are mutually exclusive.
- ~org-autotask-waitingfor~: The GTD waiting-for context. Defaults to =@waitingfor= /
   =w=.
- ~org-autotask-projects~: The GTD project list. Defaults to =project= / =p=.
- ~org-autotask-somedaymaybes~: The GTD someday/maybe list. Defaults to
  =somedaymaybe= / =m=.

For actions, there are three customizable TODO entry keywords:
- ~org-autotask-next-action-keyword~: The keyword for the next action (in the GTD
  sense). Active projects have this keyword too. Defaults to =TODO=
- ~org-autotask-done-keyword~: The keyword for a completed task or project. Defaults to
  =DONE=.
- ~org-autotask-cancelled-keyword~: The keyword for a cancelled task or project.
  Defaults to =CANCELLED=.

For clocking automation:
- ~org-autotask-clock-gated-commands~: A list of commands, which may only be invoked
  with an Org clock running.
- ~org-autotask-clock-in-actions~: a list of plists configuring automatic actions to be
  executed on clocking-in the node that has one of the configured properties.

* Usage

Set the configuration as described above, then call ~org-autotask-initialize~. Beware
that calling it multiple times in the same session may have unexpected results on the
Org variables it touches.

** Building Agenda Views

There are a few functions that can be used in ~org-agenda-custom-commands~:
- ~org-autotask-agenda-block (contexts &optional header)~: return a ~tags-todo~ form to
  be included in a custom agenda view for either a single context or a list of them.
  If a header is not passed and it's a single context, use its description as the
  header.
- ~org-autotask-agenda (context)~: return a sublist (everything except the leading key)
  for a single ~org-agenda-custom-commands~ entry.
- ~org-autotask-somedaymaybe-agenda~: return a sublist for a single custom command
  entry for the someday/maybe items.
- ~org-autotask-active-project-tasks-agenda~: return a sublist for active next actions
  that are not under any project.
- ~org-autotask-archivable-tasks~: return a ~tags~ form to be included in a custom
  agenda view that shows completed items which are not under any project.
- ~org-autotask-contextless-tasks~: return a ~tags~ form to be included in a custom
  agenda view that shows items which are not tagged with any context.

TODO example

** Elisp Automation Library

- ~org-autotask-require-org-clock~: call this from interactive commands to block them
  unless an Org clock is running. For the commands written by someone else, use
  ~my-org-clock-gated-commands~ instead.
- ~org-autotask-with-org-node-with-url (url &rest body)~: a macro to find the Org node
  with this URL across Org agenda files and then execute the body forms there.
- ~org-autotask-clock-in-node-with-url (url)~: find the Org node with this URL and
  clock it in.
- ~org-autotask-with-different-org-clock (&rest body)~: a macro to save the current Org
  clock state, clock in the current Org node, execute the body forms, and resume
  previous clocking, if any.
- ~org-autotask-insert-project (title)~: insert a new project with the given title at
  point.
- ~org-autotask-insert-waiting-for-next-action (title)~: insert a new waiting-for item
  at point.
- ~org-autotask-complete-item~: mark the item at point (a next action or a project) as
  completed.

* Comparison with other ~org~ GTD packages

** =org-gtd=

=org-gtd= provides a full prescriptive GTD implementation, covering the whole
workflow. This package, on the other hand, provides some of the building blocks to
build your own implementation without prescribing the whole workflow.

** =org-edna=

=org-edna= provides dependency management for =org= tasks for automation. While this
package also focuses on automation, it does not focus on the dependencies much. Both
packages can be used together.

* License

TODO
